name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: Manjaro

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        echo "::set-env name=FIREBASE_API_KEY::${{ secrets.FIREBASE_API_KEY }}"