name: Test secrets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print secret
      run: echo "The secret value is: ${{ secrets.SECRET_NAME }}"